---
title: "Thinking Fast and Slow"
author: "Subash Pathak"
date: "July 17, 2019"
output: html_document
 
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("rmarkdown")
```

##Book links and description
Amazon: https://www.amazon.com/Thinking-Fast-Slow-Daniel-Kahneman/dp/0374533555

* ISBN: 0374275637
* Date read: July, 2019


## Introduction
* Informed gossip
* The hope for informed gossip is that there are distinctive patterns in the errors people make
* The mental work that produces impressions, intuitions and many decisions goes on in silence in our mind
* Ability to identify and understand errors in  judgement and choice in others and ourselves; provide richer and precise language to discuss them
* Are people intuitive statisticians? 
* Reliability of the intuitive sense of statistical results from small samples
* People tend to assess the relative importance of issues by the ease with which they are retrieved from the memory- and this is largely determined by the extent of coverage in the media; in other words our actions and thought processes are hugely affected by what is being mainly fed by the media.
* If you find yourself in new situation or solving new problem, look for the familiar elements in them based on your previous experience, and act appropriately to resolve new problems.However, do not forget to evaluate how reliable is your previous experience, and do not make decision only based on heuristics judgement.

## PART I: Two Systems
#Chapter 1: Characters of the story
* Two modes of thinking: System1: operates automastically and quickly with little or no effort and no sense of volunatry control; eg. angry face of the women shown in the picture is quickly judged as angry
System2: Allocates attention to the effortful activities like complex computation. Its operations are often associated with the subjective experience of agency, choice and concentration
* The gorrila study reveals we can be blind to the obvious, and we can be blind to our own blindness
* Most of the time what you think originates in your system 1, but system 2 takes over when things get difficult
* System2 overcomes impulses arising from system1 ( system2 is in charge of self control)

#chapter 2: Attention and effort
* Add-1 and add-3 game [on/three exercise](https://psychology.stackexchange.com/questions/16531/kahnemans-add-one-three-exercise): dilating of pupil increase as the difficulty of computation increase
* Pupils are the window to your soul
* Dilation and contraction of pupil was a good measure of physical arousal that accompanies mental effort, and we could use it to understand how mind works
* system2 protects the most important activity at hand; system1 takes ove rin emergencies and assigns total priority to self protective actions
* **Law of least effort**: If there are several ways of acheiving the same goal, people will eventually gravitate towards the least demanding course of action. In the economy of action, effort is cost, and the acquistion of skill is driven by the balance of benefits and costs. Laziness is built deep into our nature.
* Avoid mental overload dividing our task into multiple easy steps, commiting intermediate results to a long term memory or to a paper rather than to an easily overloaded working memory.

#chapter 3: The Lazy controller
* Hard to do effortful computations while walking or running
* Maintenance of coherent train of thoughts and occassional involvement in effortful thinking require self-control
* People sometime expend considerable effort for long period of time without having to exert willpower. This is called "**FLOW**" coined by psychologist Mihaly.
* System1 has more influence on behavior when system2 is busy. Eg. When solving a computation you are given the choice of chocolates and fruits,and your system1 thinking comes into play and you make the choice of chocolates.
* Effort of will or self control is tiring (Baumeister's study); if you have to force yourself to do something, you are less willing or less able to  self-control when the next challenge comes around. This phenomenon is called **ego depletion**.
* example: People are first depleted by a task in which they force eat virtuous food like radish, celery resisting the temptation of cakes and chocolates. later these people will give up earlier than normal when faced with difficult cognitive challenges
* Bat and ball Problem
* Intelligence is not only the ability to reason; it is also the ability to find relevant materials in memorys and to deploy attention when needed.
* Rational people are "engaged" (more alert, more intellectually active,less willing to be satisfied with superficially attractive answers,more skeptical about their intuitions)

#chapter 4: The associative Machine
* **Associative activation**: Ideas that have been evoked triggered many other ideas; in a cascade of activities in your brain. (operation of system1)
* **Associatively coherent**: Self-reinforcing pattern of cognitive, emotional and physical responses that is both diverse and integrated
* Principles of association to three (Scottish philosopher David Hume; Enquiry concerning human understanding, 1748): resemblence, contiguity in time and place and causality.
* What is an idea: Psychologists think idea is nodes in a vast network, called associative memory, in which each idea is linked to many others
* One idea activates many other ideas; but only few stay in our consciousness, most of them are hidden
* Most of associative thinking is silent; you know far less about yourself than you feel you do
* **primimg effect**: Florida effect;  Influencing an action by the idea: Ideomotor effect
* Reciprocol priming effects tend to produce a coherent reaction: if you were primed to think of old age, you would tend to act old, and acting old would reinforce the thought of old age.
* Common admonition to act "calm and kind" regardless of how you feel is a good advice: you are likely to be rewarded by actually feeling calm and kind
* Book stranger to ourselves

#chapter 5: Cognitive Ease
* **cognitive strain** and **cognitive ease**
* Repeated experience, clear display,primed idea and good mood induce cognitive ease and they feel familiar, true, good and effortless
* When you are at ease, you are less casual and superficial in thinking whereas when you feel strained, you feel less comfortable, make few errors but you are also less intuitive and less creative than usual.
* Anything that makes it easier for the associative machine to run smoothly will also bias beliefs. A reliable way to make people believe in falsehoods is frequent repetition, and because familiarity is not easily distinguished from truth.
* When we are uncomforatable and unhappy, we lose touch with our intuition (operation of system1)
* Familiarity breeds liking. It might be a mere exposure effect; I am in a very good mood today, and my system2 is weaker than usual. I must be extra careful

#Chapter 6: Norms, Surprises and Causes
* The main function of system1 is to maintain and update the model of your personal world, which represents what is normal in it.
* [Norm Theory] https://pdfs.semanticscholar.org/9809/8ee48700173e2f09aeff48c406ef943918b5.pdf
* The automatic search for causes shapes our thinking to explain an event regardless of the cause being related to the event
* She can't accept that she was just unlucky; she needs a causal story. She will end up thinking that someone intentionally sabotaged her work.

#Chapter 7: A machine for jumping to conclusions
* Jumping to conclusions is efficient if the conclusions are likely to be correct and the costs of an occasional mistake acceptable, and if the jump saves much time and effort. Jumping to conclusions is risky when the situation is unfamiliar, the stakes are high, and there is no time to collect more information.
* System1 interprets an event based on recent memory and current context; conscious doubt is not the reportoire of system1. Uncertainty and doubt are the domain of system2.
* System2 is sometimes busy and often lazy. People are more likely to be influenced by empty persuasive messages such as commercials when they are tired and depleted.
* Associative memory contribute to general *confirmation bias*
* A deliberate search for confirming evidence, known as *positive test strategy* is how system 2 tests hypothesis. This is contrary to rules of philosophers of science who advise testing hypothesis trying to refute them. eg. when asked "is sam friendly?" different instances of sam's behavior will come to mind than when asked "is sam unfriendly?"
* People often seek data that are likely to be compatible to the beliefs they currently hold
* **Halo effect**(Exaggerated Emotional Coherence): Halo effect increases the weight of first impressions, sometimes to the point that subsequent information is mostly wasted.
* To derive the most useful information from multiple sources of evidence, you should always try to make these sources independent of each other
* Allowing the observers to influence each other effectively reduces the size of the sample, and with it the precision of the group estimate. (the jar experiment; book: wisdom of crowds)
* When there are multiple witnesses to an event, they are not allowed to discuss it before giving their testimony. The goal is not only to prevent collusion by hostile witness, it is also to prevent unbiased witnesses from influencing each other. Witnesses who exchange their experiences will tend to make similar errors in their testimony, reducing the total value of information they provide. Eliminating redundancy from your sources of information is always a good idea.
* **What you see is All there is** System1 creates coherence of stories discarding the amount and quality of the data on which the story is based. Jumping to conclusions on the basis of limited evidence and not looking for evidences unware to you is the basis of system1, and system2, being lazy follows system1 blindly sometimes.
* They made that big decision on the basis of a good report from one consultant. WYSIATI- They did not seem to realize how little information they had. They didn't want more information that might spoil their story.

#Chapter 8, 9: How Judgements Happen,Answering an easier question 
* Good mood and cognitive ease are the human equivalents of assessments of safety and familiarity
* Judgement heuristic: People fall for the quick assessment of candidate based on how confident they look when they should be using system2 for true assessment.
* Intensity matching: Tendency of using unrelated characteristics of a person to predict another characteristic. eg. predict Julie's GPA as above 3.5 based on her ability to read at an early age.
* Mental Shotgun: Conflict with irrelevant answer disrupts performance
* Substitution: If a satisfactory answer to hard question is not found quickly, System 1 will find related question that is easier and will answer it.
* The technical definition of heuristic is a simple procedure that helps find adequate, though often imperfect, answers to difficult questions
* The present state of mind looms very large when people evaluate their happiness
* He likes the project, so he thinks its costs are low and its benefits are high. Nice example of affect heuristic

## PART II: Heuristics and Biases 

##Chapter 10: Law of small numbers
* System1 is highly adept in one form of thinking- it automatically and effortlessly identifies causal connection between events, sometimes even when the connection is spurious.
* **artifacts** observations that are produced entirely by some aspect of the method of research eg. by differences in sample size
* **law of small numbers**: When we look at small samples, there is more likelihood of seeing the observations with extreme results. i.e we will see huge variation in the data than compared to larger sample size.
* The exaggerated faith in small samples is only one example of a more general illusion-we pay more attention to the content of messages than to information about their reliability, and as a result end up with a view of the world around us that is simpler and more coherent than the data justify. Jumping to conclusions is a safer sport in the world of our imagination than it is in reality.
* Statistics produce many observations that appear to beg for causal explanations but do not lend themselves to such explanations. Many facts of the world are due to chance, including accidents of sampling. Casual explanations of chance events are inevitably wrong.

##Chapter 11,12,13,14,15,16,17,18: Anchors, The science of Availability, Availability, emotions, risk, Tom W's Specialty, Linda: Less is more, Causes trump statistics, Regression to the mean, Taming Intutitve predictions
* **Anchoring effect** If you consider how much you should pay for a house, you will be influenced by the asking price. The same house will appear more valuable if its listing price is high than if it is low, even if you are determined to resist the influence of its number; the examples of anchoring effect is endless.
* **Anchoring Index**
* Plans are best case scenarios. Let's avoid anchoring on plans when we forecast actual outcomes. Thinking about ways the plan could go wrong is one way to do it.
* **Availability Heuristic** A dramatic event temporarirly increases availability of its category. A plane which receives a lot of media coverages temporarily alter your feelings about the safety of flying.
* The CEO has had several successes in a row, so the failure doesn't easily come to her mind. The availability bias is making her overconfident.
* People substitute probability for representativeness
* **Conjuction Fallacy**
* They added cheap gift to an expensive product, and made the whole deal less attractive. In this case less is more.
* You are more likely to learn something by finding surprises in your own behavior than by hearing surprising facts about people in general.
* success=talent + Luck
* Great success=a little more talent + a lot of luck
* Perhaps his second interview was less impressive than the first because he was afraid of disappointing us, but more likely it was his first that was unusually good due to regression to the mean.
* Our intuitive prediction is very favorable, but it is probably too high. Let's take into account the strength of our evidence and regress the prediction toward the mean.
* That start-up acheived an outstanding proof of concept, but we should not expect them to do as well in the future. They are still long way from the market and there is a lot of room for regression.

##Part III: Overconfidence

##Chapter 19,20,21,22,23,24: The illusion of understanding, the illusion of validity,intuitions vs. formulas, Expert Intuition: When can we trust it?, the outside view,The engine of capitalism
* Nassim Taleb notion of **narrative fallacy**: How flawed stories of the past shape our views of the world and our expectations for the future. Humans constantly fool themselves by constructing filmsy accounts of the past and believing they are true.
* **hindsight bias** :This mistake appears obvious, but it is just hindsight. You could not have known in advance.
* He is learning too much from this success story, which is too tidy. He has fallen for narrative fallacy.
* It is wise to take admissions of uncertainty seriously, but declarations of high confidence mainly tell you that an
individual has constructed a coherent story in his mind, not necessarily that the story is true.
* She is a hedgehog. She has a theory that explains everything, and it gives her the illusion that she understands the world.
* Let's decide on advance what weight to give to the data we have on the candidates' past performance. Otherwise we will give too much weight to our impression from the interviews.
* Create a list of requirements or characteristics that are independent from one another you are looking for in a candidate, and score them on a scale of 1-5 (weak-very strong) one by one.
* When evaluating expert intuition you should always consider whether there was an adequate opportunity to learn the cues, even in a regular environment.
* **The planning fallacy** : Overly optimistic forecasts of the outcome of the projects are found everywhere
* He's taking an inside view. He should forget about his own case and look for what happened in  other cases (outside view).
* **Optimistic bias** : They have an illusion of control. they seriouly underestimate the obstacles.

## Part IV: Choices

## Chapter 25,26,27,28,29,30,31,32,33,34: Bernoulli's errors, prospect theory, The endowment effect, Bad Events, The fourfold pattern,rare events, risk policies, keeping score,Reversals,Frames and Reality
* Bernoulli's point: People's choices are based not on dollar values but on pyschological values of outcomes, their utilities.
* Bernoulli's error: Both candidates are willing to accept the salary we're offering, but they won't be equally satisfied because their reference points are different. She currently has a much higher salary.
* **risk aversion**  
* When compared or weighted against each other, losses looms larger than gains.
* Considering her vast wealth, her emotional response to trivial losses and gains make no sense
* She didn't care which of the two offices she would get, but a day after the announcement was made, she was no longer willing to trade. Endowment effect!
* This reforn will not pass. those who stand to lose will fight harder than those who stand to gain
* The large impact of 0-5% illustrates possibility effect, whcih causes highly unlikely events to be weighted disproportionately more thena they deserve. eg: people are willing to pay more than the expecte dvalue for very small chance to win a large prize in lottery.
* The improvement from 95% to 100% is another qualitative change that has large impact, the certainty effect.
* People overestimate the probabilities of unlikely events; people overweight unlikely events in their decisions
* ENterpreuners and the investors who evaluate their prospects are prone both to overestimate their chances and to overweight their estimates.
* Tsunamis are very rare in Japan, but the image is so vivid and compelling that tourists are bound to overestimate their probability.
* They want people to be worried by the risk. That's why they describe it as 1 death per 1000. they're counting on denominator neglect.
* They will feel better about what happened if they manage to frame the outcome in terms of how much money they kept rather than how much they lost.

## Part V : TWo Selves

## Chapter 35,36,37,38: Two selves, Life as a story, Experienced, well-being, Thinking about life
* What we learn from the past is to maximize the qualities of our future memories, not necessarily of our future experience. This is the tyranny of remembering self.
* peak end rule and duration negelect
* Its a bad case of duration neglect when you are giving good and the bad part of your experience equal weight, although the good part lasted ten times as long as the other.
* The easiest way to increase happiness is to control your use of time. Can you find mor etime to do the things you enjoy doing?
* Nothing in life is as important as you think it is when you are thinking about it.

## Conclusions
* The perspective of remembering self is not always correct
* A moment can gain importance by altering the experience of subsequent events eg: 1 hour spent practicing guitar each day may enhance experience of many hours of playing or listening to music years later.
* Remembering self and experiencing self should both be considered because their interests do not always coincide
* The definition of rationality as coherence is impossibly restrictive; it demands adherence to rules of logic which the finite mind is not able to implement. Humans are not described by the rational-agent model.
* Deviating from normal choice is an act of commission, which requires effortful deliberation, and takes on more responsibility, and is more likely to evoke regret than doing nothing.
* System1 does X is shortcut for X occurs automatically; system2 is mobilized to do Y is shortcut for arousal increases, puplis dilate,attention is focused and activity Y is performed
* The acquisition of skills requires a regular environment,an adequate opportunities to practice,and rapid and unequivocal feedback about the correctness of thoughts and action.
* Decision makers are sometimes better able to imagine the voices of present gossipers and future critics than to hear the hesitant voice of their own doubts.




